### ISSUE TITLE
Clef Géoportail

### ISSUE THREAD

**Issue by tescrihuela** [xavierdeneux/strava-enhanced-maps#1]
Salut,

Dans ton code tu utilises la clef _an7nvfzojv5wa96dsga5nk8w_ qui est le clef utilisée par le Géoportail. Elle a pour vocation de n'être utilisée que par le portail.
Pour une clef "grand public", tu peux choisir _choisirgeoportail_ qui est une clef ouverte contenant les flux Ortho, Cartes IGN et Scan Express. Il n'y a peut-être pas besoin non plus d'afficher les parcelles cadastrales.

En tout cas l'extension est cool, c'est super !

**Comment by xavierdeneux** [comment]
Merci pour ton retour :)
