### ISSUE TITLE
Changement de 1er plan impossible en cours d'itinéraire

### ISSUE THREAD

**Issue by davidwallerick** [xavierdeneux/strava-enhanced-maps#2]
Bonjour,
très bonne idée ! Merci d'avoir déjà travaillé sur du déboguage pour le chargement de l'extension. 
Comme expliqué sur Twitter, RAS si on ne change pas de carte 1er plan en cours de création d'itinéraire.
Si on change la carte de 1er plan, aucune carte de s'affiche, et impossible de revenir à la carte initiale.
![Capture](https://user-images.githubusercontent.com/36133428/79597046-de12ea80-80e1-11ea-8c00-3c628b7c4cdd.PNG)
![image](https://user-images.githubusercontent.com/36133428/79597078-ef5bf700-80e1-11ea-9668-84be9059b9e2.png)
Messages de la console : 
![image](https://user-images.githubusercontent.com/36133428/79597124-069ae480-80e2-11ea-819d-72eabde4ac17.png)

David

**Comment by xavierdeneux** [comment]
Je ne vois que ton message aujourd'hui, désolé. Est ce que depuis le problème persiste?
